With navbar
adatsenkoLS/UJP_sport_hub pull request #4
Opened 2021-09-29 23:39 UTC by kostvick

2021-10-02 10:17 UTC, adatsenkoLS requested changes

2021-10-02 10:17 UTC, adatsenkoLS commented on app/assets/stylesheets/scaffolds.scss
> +  font-family: verdana, arial, helvetica, sans-serif;
чи потрібен цей файл?

2021-10-02 10:17 UTC, adatsenkoLS commented on app/assets/stylesheets/navbar.scss
> +  background-color: rgba(215, 33, 48, 1);
чи не краще взяти $red-main з colors.scss

2021-10-06 14:55 UTC, adatsenkoLS approved these changes

2021-10-06 14:55 UTC, merged

2021-10-08 17:54 UTC, komakur reviewed
Agree with all changes

2021-10-08 17:56 UTC, komakur commented on app/assets/stylesheets/navbar.scss
> +  background-color: rgba(215, 33, 48, 1);
та, так краще
Заміню всі кольори на змінні

2021-10-08 17:58 UTC, kostvick commented on app/assets/stylesheets/scaffolds.scss
> +  font-family: verdana, arial, helvetica, sans-serif;
він авотматично згенерувався для коли використали скафолд для юзерів, думаю можна видалити